filter_secrets: false
language: python

python:
  - '3.5'

before_install:
  - cpanm --notest Devel::Cover::Report::Coveralls

install:
  - pip3 install HookTest>=1.0.0
  - pip install coveralls

script: hooktest ./corpora --scheme epidoc --workers 3 --verbose 10 --console table --countword --allowfailure

after_success:
  - cover -test -report coveralls  
